version: "3.9"

networks:
  app-net:
    driver: overlay
    attachable: true  # เผื่อเราจะเอา container ชั่วคราวมาต่อเพื่อทดสอบ

services:
  web:
    image: nginx:1.27-alpine
    ports:
      - "8081:80"        
    networks:
      - app-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure

  echo:
    image: ealen/echo-server
    ports:
      - "8083:80"         
    networks:
      - app-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
