version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8081" 
    
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8780:80"
    depends_on:
      - backend